
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melodykke/config-repo
          username: melodykke
          password: Y223183q!
          basedir: /Users/lijing/IdeaProjects/springcloud/config/basedir
  rabbitmq:
    addresses: localhost
    username: melodykke
    password: Y223183q!
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: ["health", "info", "bus-refresh", "monitor"]